<?php

namespace App\Http\Controllers\Staff;

use App\Http\Controllers\Controller;
use App\Models\Event;
use App\Models\Participant;
use Illuminate\Http\Request;

class EventController extends Controller
{
    /**
     * Get all events created by the logged-in staff member.
     * Route: GET /api/staff/events
     */
    public function index(Request $request)
    {
        $events = Event::where('user_id', $request->user()->id)
                       ->withCount('participants')   // Adds participants_count to each event
                       ->orderBy('date', 'desc')
                       ->get();

        return response()->json($events);
    }

    /**
     * Create a new event.
     * Token is auto-generated by the model's booted() method — we don't touch it here.
     * Route: POST /api/staff/events
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name'          => 'required|string|max:255',
            'description'   => 'nullable|string',
            'date'          => 'required|date|after_or_equal:today', // Can't create past events
            'location_name' => 'nullable|string|max:255',
            'latitude'      => 'nullable|numeric|between:-90,90',    // Valid GPS range
            'longitude'     => 'nullable|numeric|between:-180,180',  // Valid GPS range
            'radius_meters' => 'nullable|integer|min:50|max:1000',   // Between 50m and 1km
        ]);

        // Associate event with the logged-in staff
        $validated['user_id'] = $request->user()->id;

        $event = Event::create($validated);

        return response()->json([
            'message' => 'Event created successfully.',
            'event'   => $event,
        ], 201);
    }

    /**
     * Update an existing event.
     * Route: PUT /api/staff/events/{event}
     */
    public function update(Request $request, Event $event)
    {
        // Make sure the logged-in staff owns this event
        if ($event->user_id !== $request->user()->id) {
            return response()->json(['message' => 'Unauthorized'], 403);
        }

        $validated = $request->validate([
            'name'          => 'sometimes|string|max:255',
            'description'   => 'nullable|string',
            'date'          => 'sometimes|date',
            'location_name' => 'nullable|string|max:255',
            'latitude'      => 'nullable|numeric|between:-90,90',
            'longitude'     => 'nullable|numeric|between:-180,180',
            'radius_meters' => 'nullable|integer|min:50|max:1000',
        ]);

        $event->update($validated);

        return response()->json([
            'message' => 'Event updated successfully.',
            'event'   => $event,
        ]);
    }

    /**
     * Delete an event (and all its participants via cascade).
     * Route: DELETE /api/staff/events/{event}
     */
    public function destroy(Request $request, Event $event)
    {
        if ($event->user_id !== $request->user()->id) {
            return response()->json(['message' => 'Unauthorized'], 403);
        }

        $event->delete();

        return response()->json(['message' => 'Event deleted successfully.']);
    }

    /**
     * PUBLIC: Validate a QR token and return basic event info.
     * This is the FIRST thing Register.jsx calls when the page loads.
     * Route: GET /api/events/validate/{token}
     *
     * Returns the event info if valid, or an error explaining why it's blocked.
     */
    public function validateToken(string $token)
    {
        // Find event by token
        $event = Event::where('token', $token)->first();

        // Layer 1: Token doesn't exist
        if (!$event) {
            return response()->json([
                'valid'   => false,
                'message' => 'Invalid QR code.',
            ], 404);
        }

        // Layer 2: Event is closed (staff set is_open to false)
        if (!$event->is_open) {
            return response()->json([
                'valid'   => false,
                'message' => 'Registration for this event is closed.',
            ], 410); // 410 Gone — resource existed but is no longer available
        }

        // All good — return event info needed by the registration form
        return response()->json([
            'valid'          => true,
            'event_id'       => $event->id,
            'name'           => $event->name,
            'date'           => $event->date,
            'location_name'  => $event->location_name,
            'latitude'       => $event->latitude,
            'longitude'      => $event->longitude,
            'radius_meters'  => $event->radius_meters,
            'is_open'        => $event->is_open,
        ]);
    }
   public function toggleRegistration(Request $request, Event $event)
    {
        if ($event->user_id !== $request->user()->id) {
            return response()->json(['message' => 'Unauthorized'], 403);
        }

        $newValue = !$event->is_open;

        $event->update(['is_open' => $newValue]);

        return response()->json([
            'is_open' => $newValue,
            'message' => $newValue ? 'Registration opened.' : 'Registration closed.',
        ]);
    }

    public function dashboardStats(Request $request)
    {
        $user = $request->user();

        $totalEvents   = Event::where('user_id', $user->id)->count();
        $openEvents    = Event::where('user_id', $user->id)->where('is_open', true)->count();
        $closedEvents  = Event::where('user_id', $user->id)->where('is_open', false)->count();
        $totalParticipants = Participant::whereHas('event', function ($q) use ($user) {
            $q->where('user_id', $user->id);
        })->count();

        return response()->json([
            'total_events'       => $totalEvents,
            'open_events'        => $openEvents,
            'closed_events'      => $closedEvents,
            'total_participants' => $totalParticipants,
        ]);
    }
}